dist: focal
sudo: required
language: generic

before_cache:
  - rm -rf $HOME/.opam/log
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - opam
    - aspcud
    - libipc-system-simple-perl
    - libstring-shellquote-perl
env:
  global:
  - NJOBS=1
  - OCAML_VERSION="4.14.0"
  matrix:
  - TEST_TARGET="8.15.2"

before_script:
  -  ./ci/keep_alive.sh &

install:
  - opam init -n -y -c ${OCAML_VERSION}
  - eval $(opam config env)
  - opam config var root
  # this somehow fails the second time...
  - opam repo add coq-released http://coq.inria.fr/opam/released || true
  # pin the coq version according to src/Makefile $(COQ_VERSION)
  - make -C src/ pin-coq
  - make -C src/ opam
  
script:
  - eval $(opam config env)
  - opam config var root
  - make -j${NJOBS} -C src/
  - make -C src/ test
