name: Vellvm Compilation Test

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        coq_version:
          - 8.15.2
        ocaml_version:
          - 4.14-flambda

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Build Environment
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-vellvm.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
